name: WolfAddons
version: '1.4'
main: com.minegolem.wolfAddons.WolfAddons
api-version: '1.20'
authors: [ WorkWolf_2 ]
softdepend:
  - Oraxen
  - PlayerAuctions
depend:
  - NBTAPI
  - CMI
  - TradeSystem
  - NFCNotes
  - QuickShop
  - ProtocolLib
commands:
  afogive:
    usage: /<command> <item_id> <player_name>
  changeshulcker:
    usege: /<command>
